### ISSUE TITLE
昨天

### ISSUE THREAD

**Issue by pandajiangbao** [ronething/guitartabs#24]
### 类型

- [ ] 指弹
- [x] 弹唱

### 歌曲名字 

Mr. - 昨天 https://music.163.com/song?id=365852&userid=339387851

**Comment by ronething** [comment]
- 暂时没有找到满意的 先 close 了
![image](https://user-images.githubusercontent.com/28869910/54976875-a74dcc00-4fd6-11e9-90e4-90ac367c0822.png)
